### ISSUE TITLE
Question: transfer repo to tree-sitter-grammars org

### ISSUE THREAD

**Issue by clason** [tree-sitter-grammars/tree-sitter-lua#42]
Hi @MunifTanjim!

Thanks for all your work on this parser; it's rock solid and part of Neovim core now (even enabled by default on `master`). But big changes are coming to the tree-sitter ecosystem (including upstream version support, publishing parsers as artefacts, new ABI for scanners), and as part of it and to help grammars deal with it, we have created a https://github.com/tree-sitter-grammars org for parsers to live under and get a consistent set of workflows and updates.

So my question: would you be interested in transferring your parser to the org? You'd retain write (but not admin) access to it, but you'd have more people able to help out with (routine) maintenance and get a shiny set of workflows. As one of the independent flagship parsers, it would be great to have you on board ;)

**Comment by MunifTanjim** [comment]
> So my question: would you be interested in transferring your parser to the org? You'd retain write (but not admin) access to it, but you'd have more people able to help out with (routine) maintenance and get a shiny set of workflows. As one of the independent flagship parsers, it would be great to have you on board ;)

Yep, of course. Sounds good.

**Comment by clason** [comment]
Easiest is to add me as an owner to this repo, or transfer it to my personal account (I can then transfer to the org.)

**Comment by clason** [comment]
(I really need **owner** privileges to access the settings and initiate the transfer. Maybe transferring the repo to my account is easier?)

**Comment by MunifTanjim** [comment]
What about now?

**Comment by clason** [comment]
That worked, transfer complete! Thank you, and welcome to the family ;)
