### ISSUE TITLE
feature: Lua syntax highlighting for load and loadstring

### ISSUE THREAD

**Issue by rweichler** [tree-sitter-grammars/tree-sitter-lua#45]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Similar to [the C syntax highlighting within strings passed to cdef](https://github.com/tree-sitter-grammars/tree-sitter-lua/blob/main/queries/injections.scm) I would like there to be Lua syntax highlighting within strings passed to load and loadstring

**Comment by rweichler** [comment]
similar to `exec_lua` here: https://github.com/nvim-treesitter/nvim-treesitter/blob/debf5816ee/queries/lua/injections.scm#L46-L53

**Comment by clason** [comment]
There's already an injection for `cdef` in the same file. If there is a valid case missing, open an issue (or, better yet, a PR) at nvim-treesitter. Nothing to be done here.
